from datetime import datetime
from typing import Protocol
from asep.ai_quotas.models import AIQuota, AIQuotaAdmission

class AIQuotaRepository(Protocol):
    def get(self, organization_id: str, user_id: str) -> AIQuota | None: ...
    def save(self, quota: AIQuota) -> AIQuota: ...
    def delete(self, organization_id: str, user_id: str) -> None: ...
    def admit(self, organization_id: str, user_id: str, started_at: datetime, ends_at: datetime) -> AIQuotaAdmission: ...
    def inspect(self, organization_id: str, user_id: str, started_at: datetime, ends_at: datetime) -> AIQuotaAdmission: ...
    def reconcile(self, reservation_id: str) -> None: ...
    def release(self, reservation_id: str) -> None: ...
