from typing import Protocol

from asep.access.models import AccessSession, Membership, Organization, User


class AccessRepository(Protocol):
    def save_organization(self, organization: Organization) -> None: ...
    def save_user(self, user: User, password_hash: str) -> None: ...
    def update_user(self, user: User) -> None: ...
    def get_user_by_email(self, email: str) -> tuple[User, str] | None: ...
    def get_user(self, organization_id: str, user_id: str) -> User | None: ...
    def list_users(self, organization_id: str) -> tuple[User, ...]: ...
    def save_membership(self, membership: Membership) -> None: ...
    def get_membership(self, organization_id: str, user_id: str) -> Membership | None: ...
    def save_session(self, session: AccessSession) -> None: ...
    def get_session_by_hash(self, token_hash: str) -> AccessSession | None: ...
    def delete_session_by_hash(self, token_hash: str) -> None: ...


__all__ = ["AccessRepository"]
