run_id: 441d4b4b-78ca-4525-b201-1394703f6f91
project_id: sample
workflow_id: software-project
execution_status: completed
current_stage: intake
created_at: '2026-07-30T14:27:21.408546Z'
updated_at: '2026-07-30T14:27:21.559486Z'
resumed_at: null
stages:
- id: intake
  status: completed
  agent_id: business-analyst
  quality_gate_id: QG-INTAKE
  attempts: 1
transition_history:
- timestamp: '2026-07-30T14:27:21.429485Z'
  run_id: 441d4b4b-78ca-4525-b201-1394703f6f91
  entity: execution
  previous_state: created
  new_state: ready
  reason: Entradas carregadas e validadas.
  component: orchestrator
- timestamp: '2026-07-30T14:27:21.429526Z'
  run_id: 441d4b4b-78ca-4525-b201-1394703f6f91
  entity: execution
  previous_state: ready
  new_state: running
  reason: Execução sequencial iniciada.
  component: orchestrator
- timestamp: '2026-07-30T14:27:21.450029Z'
  run_id: 441d4b4b-78ca-4525-b201-1394703f6f91
  entity: stage:intake
  previous_state: pending
  new_state: ready
  reason: Dependências concluídas.
  component: workflow-engine
- timestamp: '2026-07-30T14:27:21.469642Z'
  run_id: 441d4b4b-78ca-4525-b201-1394703f6f91
  entity: stage:intake
  previous_state: ready
  new_state: running
  reason: Execução da etapa iniciada.
  component: orchestrator
- timestamp: '2026-07-30T14:27:21.530590Z'
  run_id: 441d4b4b-78ca-4525-b201-1394703f6f91
  entity: stage:intake
  previous_state: running
  new_state: completed
  reason: Quality gate APPROVED.
  component: orchestrator
- timestamp: '2026-07-30T14:27:21.559486Z'
  run_id: 441d4b4b-78ca-4525-b201-1394703f6f91
  entity: execution
  previous_state: running
  new_state: completed
  reason: Todas as etapas foram concluídas.
  component: orchestrator
pending_approvals: []
errors: []
artifact_references:
- artifact_id: 565f62df-3043-44fd-a1f0-81500976a7da
  run_id: 441d4b4b-78ca-4525-b201-1394703f6f91
  project_id: sample
  stage_id: intake
  agent_id: business-analyst
  path: business-analysis/execution-summary.md
  type: markdown
  created_at: '2026-07-30T14:27:21.504390Z'
  checksum: 9d1fe7079f934eb15dbea4401d0567910b94ad570e0b9f122ce6e7409eff780f
- artifact_id: 563d0931-6e1a-4d66-9f71-1cd9fcd8ea69
  run_id: 441d4b4b-78ca-4525-b201-1394703f6f91
  project_id: sample
  stage_id: intake
  agent_id: quality-gate-engine
  path: quality-gates/intake-result.yaml
  type: yaml
  created_at: '2026-07-30T14:27:21.519748Z'
  checksum: ead5d919d1b36d4008521c10eefdfe07f1a062b3bc0b10264208ab29271f0317
