from typing import Protocol, runtime_checkable

from asep.projects.history_models import ProjectExecution, ProjectSession


@runtime_checkable
class ProjectSessionRepository(Protocol):
    def create(self, session: ProjectSession) -> None: ...
    def get(self, session_id: str) -> ProjectSession: ...
    def list_by_project(self, project_id: str) -> tuple[ProjectSession, ...]: ...


@runtime_checkable
class ProjectExecutionRepository(Protocol):
    def create(self, execution: ProjectExecution) -> None: ...
    def update(self, execution: ProjectExecution) -> None: ...
    def get(self, execution_id: str) -> ProjectExecution: ...
    def list_by_session(self, session_id: str) -> tuple[ProjectExecution, ...]: ...
    def list_by_project(self, project_id: str) -> tuple[ProjectExecution, ...]: ...


__all__ = ["ProjectExecutionRepository", "ProjectSessionRepository"]
