run_id: 4c14c4ad-3555-4b27-9ee2-93742037216c
project_id: sample
workflow_id: software-project
execution_status: completed
current_stage: intake
created_at: '2026-07-30T14:26:44.128795Z'
updated_at: '2026-07-30T14:26:44.200931Z'
resumed_at: null
stages:
- id: intake
  status: completed
  agent_id: business-analyst
  quality_gate_id: QG-INTAKE
  attempts: 1
transition_history:
- timestamp: '2026-07-30T14:26:44.135254Z'
  run_id: 4c14c4ad-3555-4b27-9ee2-93742037216c
  entity: execution
  previous_state: created
  new_state: ready
  reason: Entradas carregadas e validadas.
  component: orchestrator
- timestamp: '2026-07-30T14:26:44.135274Z'
  run_id: 4c14c4ad-3555-4b27-9ee2-93742037216c
  entity: execution
  previous_state: ready
  new_state: running
  reason: Execução sequencial iniciada.
  component: orchestrator
- timestamp: '2026-07-30T14:26:44.143654Z'
  run_id: 4c14c4ad-3555-4b27-9ee2-93742037216c
  entity: stage:intake
  previous_state: pending
  new_state: ready
  reason: Dependências concluídas.
  component: workflow-engine
- timestamp: '2026-07-30T14:26:44.154206Z'
  run_id: 4c14c4ad-3555-4b27-9ee2-93742037216c
  entity: stage:intake
  previous_state: ready
  new_state: running
  reason: Execução da etapa iniciada.
  component: orchestrator
- timestamp: '2026-07-30T14:26:44.188968Z'
  run_id: 4c14c4ad-3555-4b27-9ee2-93742037216c
  entity: stage:intake
  previous_state: running
  new_state: completed
  reason: Quality gate APPROVED.
  component: orchestrator
- timestamp: '2026-07-30T14:26:44.200931Z'
  run_id: 4c14c4ad-3555-4b27-9ee2-93742037216c
  entity: execution
  previous_state: running
  new_state: completed
  reason: Todas as etapas foram concluídas.
  component: orchestrator
pending_approvals: []
errors: []
artifact_references:
- artifact_id: d4058b4c-242f-4db4-8107-d7f7e39bdbac
  run_id: 4c14c4ad-3555-4b27-9ee2-93742037216c
  project_id: sample
  stage_id: intake
  agent_id: business-analyst
  path: business-analysis/execution-summary.md
  type: markdown
  created_at: '2026-07-30T14:26:44.174274Z'
  checksum: 356d345f937992314fbe443a181953d7ec02827fe3333bb61a5799be41339239
- artifact_id: c69cf94b-f0cb-459b-a4b4-eebd2a7e1a8d
  run_id: 4c14c4ad-3555-4b27-9ee2-93742037216c
  project_id: sample
  stage_id: intake
  agent_id: quality-gate-engine
  path: quality-gates/intake-result.yaml
  type: yaml
  created_at: '2026-07-30T14:26:44.182218Z'
  checksum: 72313e86dd236ebc9dfdebc8357ab5aee22e64bd0329706d8a6f51a50de1c934
