run_id: 80216b38-1476-4d40-8a4d-ef5490d889b2
project_id: sample
workflow_id: software-project
execution_status: completed
current_stage: intake
created_at: '2026-07-30T14:26:42.591041Z'
updated_at: '2026-07-30T14:26:42.667162Z'
resumed_at: null
stages:
- id: intake
  status: completed
  agent_id: business-analyst
  quality_gate_id: QG-INTAKE
  attempts: 1
transition_history:
- timestamp: '2026-07-30T14:26:42.617502Z'
  run_id: 80216b38-1476-4d40-8a4d-ef5490d889b2
  entity: execution
  previous_state: created
  new_state: ready
  reason: Entradas carregadas e validadas.
  component: orchestrator
- timestamp: '2026-07-30T14:26:42.617520Z'
  run_id: 80216b38-1476-4d40-8a4d-ef5490d889b2
  entity: execution
  previous_state: ready
  new_state: running
  reason: Execução sequencial iniciada.
  component: orchestrator
- timestamp: '2026-07-30T14:26:42.623547Z'
  run_id: 80216b38-1476-4d40-8a4d-ef5490d889b2
  entity: stage:intake
  previous_state: pending
  new_state: ready
  reason: Dependências concluídas.
  component: workflow-engine
- timestamp: '2026-07-30T14:26:42.631471Z'
  run_id: 80216b38-1476-4d40-8a4d-ef5490d889b2
  entity: stage:intake
  previous_state: ready
  new_state: running
  reason: Execução da etapa iniciada.
  component: orchestrator
- timestamp: '2026-07-30T14:26:42.655661Z'
  run_id: 80216b38-1476-4d40-8a4d-ef5490d889b2
  entity: stage:intake
  previous_state: running
  new_state: completed
  reason: Quality gate APPROVED.
  component: orchestrator
- timestamp: '2026-07-30T14:26:42.667162Z'
  run_id: 80216b38-1476-4d40-8a4d-ef5490d889b2
  entity: execution
  previous_state: running
  new_state: completed
  reason: Todas as etapas foram concluídas.
  component: orchestrator
pending_approvals: []
errors: []
artifact_references:
- artifact_id: 039437aa-ad2c-44cd-ab52-2c513c0700c5
  run_id: 80216b38-1476-4d40-8a4d-ef5490d889b2
  project_id: sample
  stage_id: intake
  agent_id: business-analyst
  path: business-analysis/execution-summary.md
  type: markdown
  created_at: '2026-07-30T14:26:42.645721Z'
  checksum: abe3a6b9930355f80308656311437b5c9081b49a5d9426d92542291c8b8d946c
- artifact_id: 071e1669-0da5-4f63-8b90-4e287928022f
  run_id: 80216b38-1476-4d40-8a4d-ef5490d889b2
  project_id: sample
  stage_id: intake
  agent_id: quality-gate-engine
  path: quality-gates/intake-result.yaml
  type: yaml
  created_at: '2026-07-30T14:26:42.652069Z'
  checksum: 19ea8fef9da0067ef91de467035bf356be3cb42c32aacf6197c226fd18fdf2e9
