run_id: 7798e4da-c3a5-47cf-9ff4-adcc07b8307d
project_id: sample
workflow_id: software-project
execution_status: completed
current_stage: intake
created_at: '2026-07-30T14:27:16.037726Z'
updated_at: '2026-07-30T14:27:16.234821Z'
resumed_at: null
stages:
- id: intake
  status: completed
  agent_id: business-analyst
  quality_gate_id: QG-INTAKE
  attempts: 1
transition_history:
- timestamp: '2026-07-30T14:27:16.079564Z'
  run_id: 7798e4da-c3a5-47cf-9ff4-adcc07b8307d
  entity: execution
  previous_state: created
  new_state: ready
  reason: Entradas carregadas e validadas.
  component: orchestrator
- timestamp: '2026-07-30T14:27:16.079606Z'
  run_id: 7798e4da-c3a5-47cf-9ff4-adcc07b8307d
  entity: execution
  previous_state: ready
  new_state: running
  reason: Execução sequencial iniciada.
  component: orchestrator
- timestamp: '2026-07-30T14:27:16.137935Z'
  run_id: 7798e4da-c3a5-47cf-9ff4-adcc07b8307d
  entity: stage:intake
  previous_state: pending
  new_state: ready
  reason: Dependências concluídas.
  component: workflow-engine
- timestamp: '2026-07-30T14:27:16.157889Z'
  run_id: 7798e4da-c3a5-47cf-9ff4-adcc07b8307d
  entity: stage:intake
  previous_state: ready
  new_state: running
  reason: Execução da etapa iniciada.
  component: orchestrator
- timestamp: '2026-07-30T14:27:16.208006Z'
  run_id: 7798e4da-c3a5-47cf-9ff4-adcc07b8307d
  entity: stage:intake
  previous_state: running
  new_state: completed
  reason: Quality gate APPROVED.
  component: orchestrator
- timestamp: '2026-07-30T14:27:16.234821Z'
  run_id: 7798e4da-c3a5-47cf-9ff4-adcc07b8307d
  entity: execution
  previous_state: running
  new_state: completed
  reason: Todas as etapas foram concluídas.
  component: orchestrator
pending_approvals: []
errors: []
artifact_references:
- artifact_id: 8e8e5e23-eec8-4954-8f7c-6f38b55fd26a
  run_id: 7798e4da-c3a5-47cf-9ff4-adcc07b8307d
  project_id: sample
  stage_id: intake
  agent_id: business-analyst
  path: business-analysis/execution-summary.md
  type: markdown
  created_at: '2026-07-30T14:27:16.188556Z'
  checksum: 4203be90b5b3764de573dfa6db63529a712d9862fd1492b0c6032a2df439b21a
- artifact_id: c4dafda9-12a6-486f-a809-c4302a92eec1
  run_id: 7798e4da-c3a5-47cf-9ff4-adcc07b8307d
  project_id: sample
  stage_id: intake
  agent_id: quality-gate-engine
  path: quality-gates/intake-result.yaml
  type: yaml
  created_at: '2026-07-30T14:27:16.200092Z'
  checksum: cd52be165e53bac77ebb822186b15d445ce5f349ab71d1c4f868d76f5965fd11
